chore(playground): omit stdlib when compiling printf-without-stdlib
The next step to not use stdlib is to omit the stdlib from our binary.
The size decreased a lot, from 800 kb to 9 kb. Please keep in mind that
this binary is only printing `Holy C!` to stdout.

There are a few consideration when compiling this:
- This approach might not portable, which means you might need to adjust
  something and can not use it as is.
- My gcc compiler need -fstack-protector flag to resolve error
  `undefined reference to `__stack_chk_fail'`, but you might not need
  that.